### ISSUE TITLE
page > 100

### ISSUE THREAD

**Issue by SsovaA** [Duff89/wildberries_parser#4]
Если в URL запроса товаров page > 100, то возвращается ответ с кодом 200 и пустым телом.

**Comment by Duff89** [comment]
> Если в URL запроса товаров page > 100, то возвращается ответ с кодом 200 и пустым телом.

Это особенность самого wb, откройте в браузере любой раздел и попробуйте открыть страницу 101, будет тот же эффект

**Comment by SsovaA** [comment]
Спасибо. Нашел выход. Добавил фильтр по брендам с параметром fbrand= .

**Comment by Duff89** [comment]
> Спасибо. Нашел выход. Добавил фильтр по брендам с параметром fbrand= .

Можно с помощью комбинации разных фильтров спарсить больше товаров. Например сначала взять всё по фильтру "Сначала дорогие", потом "Сначала дешевые". Но лимит в 100 страниц никуда не денется
